### ISSUE TITLE
Use Case 3.3: Add Event [ UPDATE 01 ]

### ISSUE THREAD

**Issue by u19012366** [COS301-SE-2023/Koja#137]
### Adding recurring event support

Backend:

- [x] Adapt the Event-DTO to support recuring property 
- [x] Research how google returns google events
- [x] Confirm current `getEvents` endpoint implementation to ensure it returns recurring properties
- [x] Update `createEvent` endpoint to support recurring properties 

Front end:

- [x] Adapt the Event Class to support new event DTO
- [x] Create UI component based on Google's Design
- [x] Ensure that viewing event displays recurring properties

Integration: 

- [x] Integrate Backend and Frontend components to work together

**Comment by u19012366** [comment]
Extended by one day, from August the 16th to August the 17th

**Comment by u19012366** [comment]
Front end component not completed on due date ( August the 17th ), extended by 2 days, new due date for Frontend, Backend and Integration is August the 19th

**Comment by u19012366** [comment]
Having some issues with the widget not updating as it's supposed / expected to, due date has been updated from August the 19th to August the 25th to support integration

**Comment by u19012366** [comment]
Still on track to be completed on due date ( 25th of August )

**Comment by u19012366** [comment]
Integration delayed, @UnarineLeo had issues with authentication, due date has been moved from the 25th of August to the 29th of August

**Comment by u19012366** [comment]
Integration has been delayed, some logic elements are not ligniing up as expected, due date could not be met, expected date of completion: 31 August

**Comment by u19012366** [comment]
Integration still underway - still not completed as expected or initially planned

**Comment by UnarineLeo** [comment]
Everything works perfectly, integration done
