### ISSUE TITLE
Use Case 3.3: Add Event [ UPDATE 02 ]

### ISSUE THREAD

**Issue by u19012366** [COS301-SE-2023/Koja#138]
### Adding priority Level support

General Info:
There should be 3 levels:
1. Low
2. Medium 
3. High

Backend:

- [x] Update event DTO to support priority levels properties
- [x] Refactor existing scheduling functionality for dynamic events to prioritise higher levels of priority properties
- [x] Ensure `getEvents` returns events with priority levels properties
- [x] Ensure `createEvent` supports creating events with priority level properties

FrontEnd:

- [x] Update the event class to support priority levels
- [x] Restrict priority levels to dynamic events
- [x] Ensure current UI implementation follows what was discussed

Integration:

- [x] Integrate Backend and Frontend to work together

**Comment by u19012366** [comment]
Pushed one day due to Authentication issues, from August the 14th to August the 15th

**Comment by u19012366** [comment]
Pushed by anotehr day due to Authentication issues, from August the 15th to August the 16th

**Comment by u19012366** [comment]
Due date has been updated from August the 16th to August the 25th to allow for integration

**Comment by u19012366** [comment]
Still on track to be completed on due date ( 25th of August )

**Comment by u19012366** [comment]
Integration delayed, @UnarineLeo had issues with authentication, due date has been moved from the 25th of August to the 29th of August

**Comment by u19012366** [comment]
Integration due date not met, event creation issues on the front end is causing the delay, expected completion day: 31 August

**Comment by u19012366** [comment]
Still busy with integration - not completed as expected or initially planned

**Comment by u19012366** [comment]
Estimated to be completed by the end of this day( September the 7th ) - this includes unit testing

**Comment by u19012366** [comment]
Confirmed that it is working, but some UI components need be updated for feature to work as expected

**Comment by UnarineLeo** [comment]
Integration was tested and was working well
