### ISSUE TITLE
Use Case 6.3: Train Recommender Model [ UPDATE 01 ]

### ISSUE THREAD

**Issue by u19012366** [COS301-SE-2023/Koja#142]
Add support for retraining the current model based on a list of events

AI Server Backend:

- [x] Add endpoint to server to receive data which should be used to update the current model
- [x] Add support for retaining the model based on received list items

**Comment by U18034332** [comment]
Somewhat working but still need updating for safe communication

**Comment by u19012366** [comment]
Member not present in meeting, could not confirm if due date ( August the 18th ) can be met

**Comment by u19012366** [comment]
Member ( @U18034332 ) could no meet the due date due to issues with their laptop, the due date has been extended from August the 18th to August the 25th

**Comment by U18034332** [comment]
Done, I am just not sure how the list will look like for data cleaning so that I can create trainable tensors

**Comment by u19012366** [comment]
Please elaborate on this

**Comment by u19012366** [comment]
Member could not attend standup session due to disclosed but private reasons, therefore completion cannot be fully confirmed

**Comment by u19012366** [comment]
Feature not completed due to changes requested by client this issue has been delayed
