### ISSUE TITLE
Research PyTorch and TensorFlow Models

### ISSUE THREAD

**Issue by u19012366** [COS301-SE-2023/Koja#4]
@U18034332, please delve into the existing models in PyTorch and TensorFlow that we might leverage or adapt for our project. 
In the process, ensure to provide the following information in your documentation:

- Determine potential applications of AI models within our project, and provide justification and methodology for their usage.
- Explore and document relevant PyTorch models that align with the identified tasks.
- Explore and document pertinent TensorFlow models that align with the identified tasks.

**The documentation should be comprehensive and provide a clear understanding of the models.**

### Your tasks are:
- [x] Identify and justify potential applications for AI within our project
- [x] Investigate and document relevant existing PyTorch models
- [x] Investigate and document relevant existing TensorFlow models
- [x] Compile a comprehensive final documentation

**Comment by U18034332** [comment]
Done
